server:
  http_listen_port: 39080
  grpc_listen_port: 0

clients:
  - url: http://192.168.104.152:3100/loki/api/v1/push
scrape_configs:
  - job_name: task-log-collect
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
    pipeline_stages:
      - static_labels:
          source: "nomad"
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d{3}'
          max_wait_time: 50s
          max_lines: 3000
      - match:
          selector: '{container=~".*"} |= "</taskId>"'
          stages:
            - regex:
                expression: <taskId>.*(?P<lastTwoCharacters>..)</taskId>
            - timestamp:
                source: time
                format: "2006-01-02T15:04:05.000"
            - labels:
                timestamp:
                lastTwoCharacters:
            - static_labels:
                filtered: "true"
                collect_label: "true"
      - match:
          selector: '{filtered!="true"}'
          action: drop
          drop_counter_reason: "nomad-filter"
      - labeldrop:
          - "filtered"
  - job_name: docker
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
          #filters:
          # - name: name
          # Filter logging to just our containers
        #  values: ["verification-code","airadar-report-service", "data-collect-base", "uias-server","ai.radar-attack", "ai.radar-dashboard", "ai.radar-exposed", "ai.radar-intelligence", "ai.radar-user", "ai.radar-data-cloud", " ai.radar-enterprise", "ai.radar-keywords", "airadar-message-center", "ai.radar-task", "ai.radar-vulnerability-identification", "ai.radar-xxl-job-admin", "ai.radar-xxl-job-execute", "security-analysis-engine", "task-scheduler-engine"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d{3}'
          max_wait_time: 5s
          max_lines: 300