version: '3'
services:
  promtail:
    container_name: promtail
    image: grafana/promtail:2.7.4
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./log:/var/log:rw
      # - /home/docker-work/docker/containers:/var/lib/docker/containers